name = "TFT"
uuid = "9570069e-6003-4127-8218-4c83199da40d"
authors = ["Tom Van Acker"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
